insert into TAXONDETERMINATION 
(VERNACULARNAME,I_COMMONNAMES,T_KINGDOM,T_PHYLUM,T_CLASS,T_ORDER,T_FAMILY,T_GENUS,T_SPECIES,T_SUBSPECIES)
select distinct 
  NVL(VERNACULARNAME,0),
  NVL(I_COMMONNAMES,0),
  NVL(KINGDOM,0),
  NVL(PHYLUM,0),
  NVL(CLASS,0),
  NVL(TORDER,0),
  NVL(FAMILY,0),
  NVL(GENUS,0),
  NVL(SPECIFICEPITHET,0),
  NVL(INFRASPECIFICEPITHET,0)
from IDIGBIOFLAT;

COMMIT ALL;

--select count(*) from TAXONDETERMINATION;
