insert into TAXONDETERMINATION 
(T_KINGDOM,T_PHYLUM,T_CLASS,T_ORDER,T_FAMILY,T_GENUS,T_SPECIES)
select distinct 
  NVL(KINGDOM,0),
  NVL(PHYLUM,0),
  NVL(CLASS,0),
  NVL(TORDER,0),
  NVL(FAMILY,0),
  NVL(GENUS,0),
  NVL(INFRASPECIFICEPITHET,0)
from IDIGBIOFLAT;

select * from TAXONDETERMINATION;
